import './globals.css'
import { cn } from './cn'
import Sidebar from './sidebar'

export const metadata = {
  title: 'OpenUI',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) { 
  return (
    <html lang="en" className="dark">
      <body className={cn.layout.body}>
        <div className={cn.layout.app}>
          {/* SIDEBAR */}
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  )
}
